[package]
name = "diesel-builders"
version = "0.1.0"
edition = "2024"

[dependencies]
either.workspace = true
diesel.workspace = true
diesel-relations.workspace = true
diesel-additions.workspace = true
anyhow.workspace = true
typed_tuple.workspace = true
diesel-builders-macros.workspace = true

[dev-dependencies]
diesel = { workspace = true, features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }

[lints]
workspace = true