[package]
name = "validation-errors"
version = "0.1.0"
edition.workspace = true

[dependencies]
diesel.workspace = true
diesel-builders.workspace = true
thiserror.workspace = true

[lints]
workspace = true
