[package]
name = "diesel-additions"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel.workspace = true
anyhow.workspace = true
typed_tuple.workspace = true
diesel-builders-macros.workspace = true

[lints]
workspace = true